pipelineJob('cENM_Design_Teams_CRD') {
  description ('ENM Cloud Native Design Teams CRD pipeline - autogenerated using JobDSL - all manual changes will be overwritten!')
  concurrentBuild(allowConcurrentBuild = true)
    logRotator {
      numToKeep(100)
    }
    parameters {
        stringParam('environment_name', '','The deployment name to run the job against')
        stringParam('product_set_version', '','Provide cloud native product set version')
        labelParam('slave') {
          defaultValue("${CNRA_CRD_Job_Agents}")
          description('')
        }
    }
    definition {
      cpsScm {
        scm {
          git {
            branch('dcrd')
            remote {
              credentials('lciadm100_private_key')
              url("${GERRIT_MIRROR}/OSS/com.ericsson.oss.containerisation/eric-enm-integration-pipeline-code")
            }
          }
        }
        scriptPath("Jenkins/Jenkinsfile/JenKinsfilecrd")
        lightweight(lightweight = true)
      }
    }
}