import java.io.File

String cenmDesignTeamDeployments = readFileFromWorkspace('cENM_design_team_deployments.csv')
cenmDesignTeamDeployments.eachLine{
    deploymentData -> createDesignTeamWrapperJob(deploymentData)
}

String deploymentName
String deploymentId
String deploymentSize
def createDesignTeamWrapperJob(deploymentData){
    deploymentName = deploymentData.split(',')[0]
    deploymentId = deploymentData.split(',')[1]
    deploymentSize = deploymentData.split(',')[2]
    jenkinsFile = 'Jenkins/Pipeline/CNRA_Wrapper_Job_Pipeline.groovy'
    pipelineJob(deploymentName){
        description ('cENM Design Team Install/Upgrade/TAF Pipeline for ' + deploymentName + ' - autogenerated using JobDSL - all manual changes will be overwritten!')
        parameters {
            choiceParam(
                'job_type',
                ['install', 'install_only', 'upgrade', 'taf_only', 'teardown'],
                '''Install - runs Teardown, Install, Add Licenses, Update Trust Profiles (option <b>run_taf</b> runs TAF Testware)<br>Install Only (for deployments without Netsim) - runs Teardown, Install only on a cENM Deployment <b>without Netsim</b> (option <b>run_taf</b> runs TAF Testware)<br>Upgrade - runs Upgrade (option <b>run_taf</b> runs TAF Testware)<br>TAF Only - runs TAF Testware<br>Teardown - runs Teardown'''
            )
            choiceParam(
                'Artifact_type',
                ['csar_lite', 'csar', 'snapshot_csar_lite'],
                '''This parameter acts as the flow controller to select the deployment mechanism either csar, csar_lite, or snapshot_csar_lite<br>
<b>csar_lite</b> - Ideal for Single Instance and Multi Instance environments<br><b>csar</b> - Ideal for Production environments<br><b>snapshot_csar_lite</b> - For experimental cENM CSAR Package Installs - snapshot_csar_lite_location parameter must be populated when this is chosen'''
            )
            stringParam(
                'product_set_version',
                '',
                '''Provide cENM product set version that you want on your deployment. The <a href="https://pdu-oss-tools4.seli.wh.rnd.internal.ericsson.com/cenm_dashboard/#dashboard"/>cENM dashboard</a> shows the latest install and upgrade baselines.<br>It is recommended to use cENM Green PS when installing or upgrading cENM<br><b>Required for Install, Install Only, Upgrade & TAF</b>'''
            )
            stringParam(
                'snapshot_csar_lite_location',
                '',
                '''Provide the .csar hyperlink generated from the kgb+N job for the snapshot_csar_lite<br><b>Required for Install or Upgrade jobs where snapshot_csar_lite is chosen as Artifact_type</b> - ignore if using 'csar_lite' or 'csar' options'''
            )
            stringParam(
                'snapshot_integration_key_value_pairs',
                '',
                '''Provide the snapshot integration key value pairs in the format: For a single key value key_name##key_value<br>If multiple key values are present these can be appended with delimiter of @@<br><b>Optional for Install, Install Only, Upgrade</b>'''
            )
            stringParam(
                'environment_name',
                deploymentId,
                '''The deployment to run the job against<br><b>Required for Install, Install Only, Upgrade, TAF Only, Teardown</b>'''
            )
            choiceParam(
                'stage_area',
                ['ci_internal', 'drop'],
                '''This parameter acts as the flow controller to download charts from internal area or release area<br>There are 2 options, "ci_internal" and "drop".<br>When ci_internal is selected the individual chart will be selected from "proj-enm-dev-internal-helm" repository, which means the charts have not been verified through the MTE pipeline<br>When drop is selected this means individual chart will be selected from "proj-enm" repository and MTE has been verified and cENM install or cENM UG has passed<br><b>Required for Install, Install Only, Upgrade</b>'''
            )
            stringParam(
                'deployment_size',
                deploymentSize,
                '''<b>Required for Install, Install Only, Upgrade</b>'''
            )
            stringParam(
                'backup_name',
                '',
                '''This parameter is required for automatic pre-upgrade backup from product set 23.07.65-1 onwards<br><b>Required for Upgrade</b>'''
            )
            stringParam(
                'mt_utils_version',
                'RELEASE',
                '''This is the version of the scripts available in Nexus<br>We recommend you always use RELEASE<br>However, if there is an issue with RELEASE please use one of the versions available <a href="https://arm1s11-eiffel004.eiffel.gic.ericsson.se:8443/nexus/content/repositories/releases/com/ericsson/mtg/utils/">here</a><br><b>Required for Install, Install Only, Upgrade, TAF Only</b>'''
            )
            choiceParam(
                'nodesCleanUp',
                ['NO', 'YES'],
                '''Choose NO if NSS Network is 1.8K, choose YES if NSS Network is 2K or 15K<br>Required for <b>Update Trust Profiles</b> as part of Install<br><b>Required for Install</b>'''
            )
            stringParam(
                'simdep_release',
                '',
                '''TLS SimDep version<br>Example: 1.5.773<br>Required for <b>Update Trust Profiles</b> as part of Install<br>Can be retrieved from <a href="https://confluence-oss.seli.wh.rnd.internal.ericsson.com/display/PDUCD/NSS+Delivery+Mail+Communications">NSS Delivery Communications confluence page</a><br>Please use TLS simdep version as <b>1.5.744</b>. If NETSim version is <b><u>less than NSS 23.06.</u></b><br>Please use TLS Simdep version as <b>1.5.773</b>. If NETSim version is <b><u>equal or greater than NSS 23.06</u></b>.<br><b>Required for Install</b>'''
            )
            booleanParam(
                'run_taf',
                false,
                '''Check box to run TAF<br><b>Required for Install with TAF, Install Only with TAF, Upgrade with TAF</b><br>Automatically set to <b>true</b> for TAF Only builds'''
            )
            textParam(
                'testware_items',
                '',
                '''Insert your snippets in the format:<br>
<pre>
&lt;item-group parallel=&quot;false&quot;&gt;
    &lt;item timeout-in-seconds=&quot;480&quot;&gt;
        &lt;name&gt;External IdP Authorization Test Sync - Skyfall&lt;/name&gt;
        &lt;component&gt;com.ericsson.oss.itpf.security.sso:ERICTAFsinglesignon-testware_CXP9031665&lt;/component&gt;
        &lt;suites&gt;ExternalIdp_Authorization_TestSync.xml&lt;/suites&gt;
    &lt;/item&gt;
&lt;/item-group&gt;
</pre>
<b>Required for Install with TAF, Install Only with TAF, Upgrade with TAF, TAF Only</b>'''
            )
            stringParam(
                'internal_nodes',
                'amos_1,cmserv_1,fmalarmprocessing_1,fmalarmprocessing_2,fmalarmprocessing_3,fmalarmprocessing_4,fmalarmprocessing,fmx_1,fmx_2,itservices_1,itservices-1-internal,jms_1,opendj_1,opendj_2,openidm_0,openidm_1,scripting_1,sps_1',
                '''Enter the value for the parameter taf.config.dit.deployment.internal.nodes<br> options are:<br> amos_1,cmserv_1,fmalarmprocessing_1,fmalarmprocessing_2,fmalarmprocessing_3,fmalarmprocessing_4,fmalarmprocessing,fmx_1,fmx_2,itservices_1,itservices-1-internal,jms_1,opendj_1,opendj_2,openidm_0,openidm_1,scripting_1,sps_1<br><b>Required for Install with TAF, Install Only with TAF, Upgrade with TAF, TAF Only</b>'''
            )
            stringParam(
                'mt_csv_file_uri',
                '',
                '''Enter the value for the MT_CSV_FILE_URI. If using a custom csv file, it can be placed in the <a href="https://ci-portal.seli.wh.rnd.internal.ericsson.com/dmt/uploadSnapshot/">CI Staging Area</a> and link added above<br>If left blank, the default version that will be used is https://arm1s11-eiffel004.eiffel.gic.ericsson.se:8443/nexus/content/sites/tor/enm-maintrack-central-test-datasource/${central_csv_version}/maintrack/csv/nodeToAdd_2K.csv <br>The central_csv_version is automatically retrieved from the chosen product set<br><b>Required for Install with TAF, Install Only with TAF, Upgrade with TAF, TAF Only</b>'''
            )
            labelParam('CNRA_Wrapper_Job_Agents') {
                defaultValue("${CNRA_Wrapper_Job_Agents}")
                description('Agents used to run CNRA Wrapper Job, do not change.')
            }
        }
        logRotator {
            numToKeep(40)
        }
        definition {
            cps {
                script(readFileFromWorkspace(jenkinsFile))
                sandbox(true)
            }
        }
    }
}
